apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: haziness8921/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: haziness8921/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    # - image: haziness8921/client
    #   context: client
    #   sync:
    #     manual:
    #       - src: src/**/*.ts*
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile.dev
    - image: haziness8921/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*.yml
deploy:
  kubectl: {}